[package]
name = "mio-echo-tcp"
version = "0.2.0"
edition = "2021"
license = "MIT"

[target.'cfg(any(unix, target_os="wasi"))'.dependencies]
env_logger = { version = "0.9.0", default-features = false }
mio = { version = "0.8.11", features = ["os-poll", "net"], default-features = false }
